apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: amelgm/appdjango:v2
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-service
  namespace: default  # Assurez-vous que le namespace est correctement spécifié ici
spec:
  selector:
    app: app-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort


