# Generated by Django 4.2.7 on 2023-11-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_name_author_last_name_author_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='uniqueId',
            new_name='id',
        ),
    ]
