# Generated by Django 4.2.7 on 2023-11-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_uniqueid_bookinstance_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="imprint",
            field=models.CharField(default="0", max_length=200),
        ),
    ]
